services:
  reddit_collector:
    build: get_reddits/
    volumes:
      - ./get_reddits/:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017

  etl:
    build: etl_job
    volumes:
      - ./etl_job/:/app
    depends_on:
      - mongodb
      - postgresdb

  postgresdb:
    image: postgres
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reddits_pgdb
